jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install buildozer cython

      - name: Install Android SDK & build tools
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-11-jdk
          mkdir -p ~/.buildozer/android/platform/android-sdk
          cd ~/.buildozer/android/platform/android-sdk
          wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip
          mkdir cmdline-tools
          mv cmdline-tools/* cmdline-tools/
          yes | cmdline-tools/bin/sdkmanager --sdk_root=. "platform-tools" "platforms;android-33" "build-tools;33.0.2" "ndk;25.2.9519653"

      - name: Build APK
        run: |
          buildozer android debug
