name: Build APK

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y zip unzip openjdk-17-jdk python3-pip libncurses5

    - name: Install Buildozer
      run: |
        pip install --upgrade pip
        pip install buildozer cython

    - name: Set up Android SDK
      run: |
        mkdir -p $HOME/android-sdk
        cd $HOME/android-sdk
        curl -o sdk.zip https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip
        unzip sdk.zip -d cmdline-tools
        mv cmdline-tools cmdline-tools-latest
        mkdir cmdline-tools
        mv cmdline-tools-latest cmdline-tools/latest
        yes | cmdline-tools/latest/bin/sdkmanager --licenses
        cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-31" "build-tools;31.0.0" "ndk;23.1.7779620"

    - name: Build APK
      run: |
        export ANDROID_SDK_ROOT=$HOME/android-sdk
        buildozer android debug
