name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libncurses5 zip unzip openjdk-17-jdk wget git python3-pip
        pip install --upgrade pip
        pip install buildozer cython virtualenv

    - name: Set up Android SDK
      run: |
        mkdir -p ~/.android/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O cmdline-tools.zip
        unzip -q cmdline-tools.zip
        mv cmdline-tools ~/.android/cmdline-tools/tools
        yes | ~/.android/cmdline-tools/tools/bin/sdkmanager --sdk_root=${HOME}/.android \
          "platform-tools" "platforms;android-31" "build-tools;33.0.2" "cmdline-tools;latest"
        yes | ~/.android/cmdline-tools/tools/bin/sdkmanager --licenses
        echo "${HOME}/.android/platform-tools" >> $GITHUB_PATH
        echo "${HOME}/.android/build-tools/33.0.2" >> $GITHUB_PATH

    - name: Initialize Buildozer
      run: |
        buildozer init || true

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: safespot-debug-apk
        path: bin/*.apk
