name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y zip unzip openjdk-17-jdk python3-pip libncurses6

    - name: Install Buildozer
      run: |
        pip install --upgrade pip
        pip install buildozer cython

    - name: Set up Android SDK
      run: |
        mkdir -p ~/.buildozer/android/platform
        yes | sdkmanager --licenses || true
      env:
        JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64

    - name: Accept Android SDK Licenses and Install Build Tools
      run: |
        wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O cmdline-tools.zip
        unzip -q cmdline-tools.zip
        mkdir -p ~/.android/cmdline-tools
        mv cmdline-tools ~/.android/cmdline-tools/tools
        yes | ~/.android/cmdline-tools/tools/bin/sdkmanager --sdk_root=${HOME}/.android "platform-tools" "platforms;android-31" "build-tools;33.0.2" "cmdline-tools;latest"
        yes | ~/.android/cmdline-tools/tools/bin/sdkmanager --licenses
        export PATH=$HOME/.android/cmdline-tools/tools/bin:$PATH

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: my-app-release
        path: bin/*.apk
