name: Build APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libncurses6 zip unzip openjdk-17-jdk wget git python3-pip
          pip install --upgrade pip
          pip install buildozer cython virtualenv

      - name: Accept Android SDK Licenses
        run: yes | sdkmanager --licenses || true

      - name: Initialize Buildozer
        run: buildozer init || true

      - name: Build APK
        run: buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: safespot-debug-apk
          path: bin/*.apk
