name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            ccache \
            git \
            zip unzip \
            openjdk-17-jdk \
            libncurses5 \
            libtinfo5 \
            libffi-dev \
            libssl-dev \
            python3-pip \
            python3-setuptools

      - name: Install Buildozer and Cython
        run: |
          pip install --upgrade pip
          pip install buildozer cython

      - name: Accept Android SDK Licenses
        run: |
          mkdir -p ~/.buildozer
          echo "[buildozer]" > ~/.buildozer/global.json
          echo "android.accept_sdk_license = True" >> ~/.buildozer/global.json

      - name: Set Buildozer API and Build Tools versions
        run: |
          sed -i 's/^android.api =.*/android.api = 30/' buildozer.spec || echo "android.api = 30" >> buildozer.spec
          sed -i 's/^android.build_tools =.*/android.build_tools = 30.0.3/' buildozer.spec || echo "android.build_tools = 30.0.3" >> buildozer.spec

      - name: Initialize Buildozer (if missing)
        run: |
          if [ ! -f buildozer.spec ]; then buildozer init; fi

      - name: Build APK
        run: buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: MyApp-APK
          path: bin/*.apk
