name: Build APK with Buildozer

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            zip unzip git openjdk-17-jdk python3-pip libffi-dev \
            libssl-dev libsqlite3-dev libjpeg-dev \
            zlib1g-dev libncursesw5-dev libtinfo5

      - name: Install Buildozer and Cython
        run: |
          pip install --upgrade pip
          pip install cython==0.29.36
          pip install buildozer

      - name: Set up Android SDK manually
        run: |
          mkdir -p "$HOME/android-sdk/cmdline-tools"
          curl -o tools.zip -L --retry 5 --retry-delay 5 \
            https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip -q tools.zip -d "$HOME/android-sdk/cmdline-tools"
          mv "$HOME/android-sdk/cmdline-tools/cmdline-tools" "$HOME/android-sdk/cmdline-tools/latest"

      - name: Accept Android SDK Licenses
        run: |
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Install Android SDK Build Tools and platform-tools
        run: |
          $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager \
            "platform-tools" "platforms;android-31" "build-tools;33.0.2" "ndk;25.1.8937393"

      - name: Set environment variables
        run: |
          echo "ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
          echo "$HOME/android-sdk/platform-tools" >> $GITHUB_PATH
          echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$HOME/android-sdk/build-tools/33.0.2" >> $GITHUB_PATH

      - name: Initialize Buildozer
        run: |
          buildozer init
          sed -i 's/^#.*android.sdk_path =.*/android.sdk_path = \$HOME\/android-sdk/' buildozer.spec

      - name: Build APK
        run: buildozer android debug
