name: Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          autoconf automake libtool pkg-config \
          build-essential libffi-dev libssl-dev \
          git zip unzip openjdk-17-jdk python3-pip \
          libltdl-dev

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Upgrade pip and install build tools
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade Cython buildozer python-for-android

    - name: Install Android NDK (r25b)
      run: |
        mkdir -p $HOME/.buildozer/android/platform
        wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
        unzip -q android-ndk-r25b-linux.zip -d $HOME/.buildozer/android/platform
        rm android-ndk-r25b-linux.zip

    - name: Install Android SDK + Platform Tools
      run: |
        mkdir -p $HOME/.buildozer/android/platform
        wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
        unzip -q commandlinetools-linux-11076708_latest.zip -d $HOME/.buildozer/android/platform
        rm commandlinetools-linux-11076708_latest.zip
        mkdir -p $HOME/.buildozer/android/platform/android-sdk/cmdline-tools
        mv $HOME/.buildozer/android/platform/cmdline-tools $HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest
        yes | $HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=$HOME/.buildozer/android/platform/android-sdk "platform-tools" "platforms;android-33" "build-tools;33.0.2"

    - name: Build APK
      run: |
        export ANDROIDSDK=$HOME/.buildozer/android/platform/android-sdk
        export ANDROIDNDK=$HOME/.buildozer/android/platform/android-ndk-r25b
        export PATH=$ANDROIDSDK/platform-tools:$PATH
        buildozer -v android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: safespot-apk
        path: bin/*.apk
