name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y zip unzip git python3-pip build-essential \
            libssl-dev libffi-dev zlib1g-dev libjpeg-dev openjdk-17-jdk \
            liblzma-dev ccache
          pip install --upgrade pip
          pip install cython
          pip install buildozer

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Android SDK Licenses
        run: yes | sdkmanager --licenses

      - name: Install Android SDK Build Tools
        run: |
          sdkmanager "build-tools;33.0.2" "platforms;android-33"

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: safespot-debug-apk
          path: bin/*.apk
