name: Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          autoconf automake libtool pkg-config \
          build-essential libffi-dev libssl-dev \
          git zip unzip openjdk-17-jdk python3-pip \
          libltdl-dev

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Upgrade pip and install build tools
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade Cython buildozer python-for-android

    - name: Pin NDK version (r25b)
      run: |
        ANDROID_SDK_ROOT=$HOME/.buildozer/android/platform/android-sdk
        ANDROID_NDK_ROOT=$HOME/.buildozer/android/platform/android-ndk-r25b
        mkdir -p $ANDROID_SDK_ROOT
        wget https://dl.google.com/android/repository/android-ndk-r25b-linux.zip
        unzip -q android-ndk-r25b-linux.zip -d $HOME/.buildozer/android/platform
        rm android-ndk-r25b-linux.zip

    - name: Build APK
      run: |
        buildozer -v android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: safespot-apk
        path: bin/*.apk
